include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - web/**
    - windows/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - prefer_final_locals
    - always_declare_return_types
